# Dataverse API configuration
dataverse:
  url: https://datasets.socialhistory.org
  connectTimeoutMs: 5000
  readTimeoutMs: 10000

# The datasets Dataverse ids
datasets:
  coins: 1496
  wages: 1488

# Fields of the CSV
fields:
  UID: "Record identifier"
  TYPEID: "Coin type identifier"
  SOURCE: "Source of record"
  MINT: "Location of mint house"
  AUTHORITY: "Authority coin issuer"
  DATE: "Minting period"
  DATEfrom: "Minting start date"
  DATEto: "Minting end date"
  CoinNAME: "Name of coin"
  ALLOY: "Type of metal"
  VALUEd: "Value in deniers"
  QTTYcoins: "No. of coints minted"
  FINEness: "Purity"
  WEIGHTraw: "Troy mark weight (all materials)"
  WEIGHTfine: "Troy mark weight (fine metal)"
  TAILLE: "No. of coins in a Troy mark"
  AUTHORITY_SUPRA: "Higher authority coin issuer"
  ALT_CoinNAME: "Name of coin (alternative)"
  ALT_TYPEID: "Coin type identifier (alternative)"
  VALUE_HourlyWAGE: "Value in hourly wages"
